### ISSUE TITLE
[Android] [release] ...assets_icons_check.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..

### ISSUE THREAD

**Issue by MaxInMoon** [wix/react-native-ui-lib#117]
When making a release build on Android an error appears:

**Error**

`assets_icons_check.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..`

from

```
> Task :app:bundleReleaseJsAndAssets

...

myapp/android/app/build/intermediates/res/merged/release/drawable-xhdpi/node_modules_reactnativeuilib_src_assets_icons_check.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.


> Task :app:processReleaseResources
Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
        at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
        at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

```

**Version**
"react-native": "0.53.3",
"react-native-ui-lib": "^3.3.32",

**Comment by MaxInMoon** [comment]
**Solution**: add `android.enableAapt2=false` into `android/gradle.properties` file. (found [here](https://github.com/react-navigation/react-navigation/issues/1976#issuecomment-325019683))

**Comment by rt2zz** [comment]
is this a requirement for all release building using react-native-ui-lib?

**Comment by MaxInMoon** [comment]
@rt2zz I built both iOS and Android release versions, and I only met this error on Android (did I answer to your question?)
