### ISSUE TITLE
Importing the Button component causes errors in Jest

### ISSUE THREAD

**Issue by badmacstone** [wix/react-native-ui-lib#1205]
### Describe the bug
The `Button` component (maybe others too) causes an error in Jest tests: `TypeError: Cannot read property 'then' of undefined`

Stack trace:
```
at setAccessibility (node_modules/react-native-ui-lib/src/helpers/Constants.js:58:3)
at Object.<anonymous> (node_modules/react-native-ui-lib/src/helpers/Constants.js:63:1)
at Object.<anonymous> (node_modules/react-native-ui-lib/src/style/typography.js:2:1)
```

### To Reproduce
Simply importing the `Button` component in any test file causes the error.

### Expected behavior
I would expect to not cause any errors at all.

### Code snippet
This very trivial test causes the error. As you can see already importing it causes the error.
```
import Button from '../src/components/Button';

describe('Button component', () => {
    it('trivial', () => {
        expect(true).toBe(etrue)
    });
});
```

### Additional context
`react-native: 0.61.5`
`react-native-ui-lib: 5.20.3`
`jest: 26.1.0`

**Comment by ethanshar** [comment]
You might need to mock some stuff in react-native 
For instance Our Button uses our Constants which has this code 
```
AccessibilityInfo.isScreenReaderEnabled().then(isScreenReaderEnabled => {
    accessibility.isScreenReaderEnabled = isScreenReaderEnabled;
  });
```

So you might want to mock this part 
for instance
```
const reactNative = jest.requireActual('react-native');
jest.spyOn(reactNative.AccessibilityInfo, 'isScreenReaderEnabled').mockImplementation(() => new Promise.resolve(false));
```

**Comment by ethanshar** [comment]
Closing due to inactivity. 
Feel free to reopen if issue still relevant
