### ISSUE TITLE
Package react-native-ui-lib contains invalid configuration: "dependency.platforms.ios.project" is not allowed

### ISSUE THREAD

**Issue by pascal-maker** [wix/react-native-ui-lib#2269]
## Description
when trying to reset cache using yarn start reset--cache i get the warning Package react-native-ui-lib contains invalid configuration: "dependency.platforms.ios.project" is not allowed.  This in the process of cleaning the cache

### Related to

- [ ] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

#### Actual behavior
I get a warning saying dependency.platforms.ios.project" is not allowed.

### Code snippet
ovia-master-2 % yarn  start --reset-cache
yarn run v1.22.19
warning ../../package.json: No license field
$ react-native start --reset-cache
warn Package react-native-ui-lib contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
error listen EADDRINUSE: address already in use :::8081.
Error: listen EADDRINUSE: address already in use :::8081
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at /Users/pascalmusabyimana/Desktop/Lovia-master-2/node_modules/metro/src/index.flow.js:398:14
    at new Promise (<anonymous>)
    at earlyPortCheck (/Users/pascalmusabyimana/Desktop/Lovia-master-2/node_modules/metro/src/index.flow.js:394:11)
    at exports.runServer (/Users/pascalmusabyimana/Desktop/Lovia-master-2/node_modules/metro/src/index.flow.js:155:9)
    at Object.runServer [as func] (/Users/pascalmusabyimana/Desktop/Lovia-master-2/node_modules/@react-native-community/cli-plugin-metro/build/commands/start/runServer.js:123:49)
    at async Command.handleAction (/Users/pascalmusabyimana/Desktop/Lovia-master-2/node_modules/@react-native-community/cli/build/index.js:142:9)

```


```

### Environment

- React Native version: 0.70
- React Native UI Lib version:

### Affected platforms

- [ x] Android
- [ x] iOS
- [ ] Web

**Comment by LazyAfternoons** [comment]
Duplicate of #2119
