### ISSUE TITLE
Add an 'isAlway' and 'isOffline' property to the Avatar component

### ISSUE THREAD

**Issue by mblodorn** [wix/react-native-ui-lib#24]
Or something like:

```
<Avatar status={Avatar.status.online} />
<Avatar status={Avatar.status.away} />
<Avatar status={Avatar.status.offline} />

```

To make it customizable but allow only one status.

What do you think? I can implement that if you wish. 👍

**Comment by ethanshar** [comment]
Hey @mblodorn, 
I like the the option where you send an actual status, since you have more that 2 options it makes more sense. 
I would love to get a PR for that, just remember it needs to be backwards compatible (:

**Comment by mblodorn** [comment]
Nice,

I'll make sure that it is backward compatible.

Could you provide me more info about how to setup my environment @ethanshar? Thanks!

**Comment by ethanshar** [comment]
@mblodorn 
- clone the project
- run `yarn` to install all modules
- run `yarn start` to start packager
- on another terminal run `yarn [ios|android]` to run the example project. (for Android you will need to open the emulator first)

let me know if u need more help.

**Comment by mblodorn** [comment]
Hey @ethanshar, I have free time today and when I ran yarn to install all modules the following error showed up:

```
$ yarn
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/babel-eslint/-/babel-eslint-7.2.3.tgz: connect ETIMEDOUT 10.42.127.163:443".
info If you think this is a bug, please open a bug report with the information provided in "C:\\projects\\react-native-ui-lib\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Looks like it's trying to install from a private repository. Can you help me with that? Thanks! :)

**Comment by ethanshar** [comment]
@mblodorn, 
Sorry again for the late response. 
I tried installing the library using yarn when my npm artifactory set to the public one, and it works. 
do you still get this error ?

**Comment by mblodorn** [comment]
Yes, I still am getting this error. Here is the log with --verbose enabled:
```

blodo@DESKTOP-VN0G79D MINGW32 /c/projects/react-native-ui-lib (master)
$ yarn install --verbose
yarn install v0.27.5
verbose 0.571 Checking for configuration file "C:\\projects\\react-native-ui-lib\\.npmrc".
verbose 0.572 Checking for configuration file "C:\\Users\\blodo\\.npmrc".
verbose 0.572 Checking for configuration file "C:\\Program Files\\nodejs\\.npmrc".
verbose 0.572 Checking for configuration file "C:\\projects\\react-native-ui-lib\\.npmrc".
verbose 0.572 Checking for configuration file "C:\\projects\\.npmrc".
verbose 0.573 Checking for configuration file "C:\\projects\\react-native-ui-lib\\.yarnrc".
verbose 0.573 Checking for configuration file "C:\\Users\\blodo\\.yarnrc".
verbose 0.573 Found configuration file "C:\\Users\\blodo\\.yarnrc".
verbose 0.573 Checking for configuration file "C:\\Program Files\\nodejs\\.yarnrc".
verbose 0.573 Checking for configuration file "C:\\projects\\react-native-ui-lib\\.yarnrc".
verbose 0.573 Checking for configuration file "C:\\projects\\.yarnrc".
verbose 0.575 current time: 2017-09-06T12:34:25.850Z
[1/4] Resolving packages...
verbose 0.78 Performing "GET" request to "https://registry.yarnpkg.com/hoist-non-react-statics".
verbose 0.782 Performing "GET" request to "https://registry.yarnpkg.com/react-native-interactable".
verbose 1.2 Request "https://registry.yarnpkg.com/hoist-non-react-statics" finished with status code 200.
verbose 1.208 Request "https://registry.yarnpkg.com/react-native-interactable" finished with status code 200.
[2/4] Fetching packages...
verbose 1.256 Performing "GET" request to "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/react-native-blur/-/react-native-blur-3.1.2.tgz".
verbose 1.261 Performing "GET" request to "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/babel-cli/-/babel-cli-6.24.1.tgz".
verbose 1.269 Performing "GET" request to "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/babel-preset-es2015/-/babel-preset-es2015-6.24.1.tgz".
verbose 1.269 Performing "GET" request to "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/babel-preset-react-native/-/babel-preset-react-native-1.9.1.tgz".
verbose 1.271 Performing "GET" request to "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/enzyme/-/enzyme-2.9.1.tgz".
verbose 1.271 Performing "GET" request to "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/eslint/-/eslint-3.19.0.tgz".
verbose 1.274 Performing "GET" request to "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/eslint-config-airbnb/-/eslint-config-airbnb-14.1.0.tgz".
verbose 1.279 Performing "GET" request to "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/eslint-plugin-jsx-a11y/-/eslint-plugin-jsx-a11y-4.0.0.tgz".
verbose 23.267 Error: connect ETIMEDOUT 10.42.124.63:443
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
error An unexpected error occurred: "https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/react-native-blur/-/react-native-blur-3.1.2.tgz: connect ETIMEDOUT 10.42.124.63:443".
info If you think this is a bug, please open a bug report with the information provided in "C:\\projects\\react-native-ui-lib\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


```

**Comment by inbalwix** [comment]
Support was added. Issue resolved.
